# Generated by Django 5.1 on 2024-10-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_watchlist_avg_rating_watchlist_number_of_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
