# Generated by Django 5.1 on 2024-10-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_rename_created_at_review_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='create',
            new_name='created',
        ),
    ]
